name = "react-basic"
type = "javascript"
account_id = "05beeec529b88e2dcba42fff2ab37405c7585"
workers_dev = true
compatibility_date = "2026-01-02"  # 配置兼容日期

# 配置静态文件目录
site = { bucket = "./dist", entry-point = "workers-site" }

# 配置入口文件
main = "/index.html"
